version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8090:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./../wordpress-data/wp-content:/var/www/html/wp-content 

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
       - ./../wordpress-data/db:/var/lib/mysql
